# Generated by Django 4.1.1 on 2023-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tweet_id', models.IntegerField()),
                ('in_reply_to_status_id', models.IntegerField()),
                ('in_reply_to_screen_name', models.CharField(max_length=60)),
                ('usertag_id', models.IntegerField(unique=True)),
                ('is_quote_status', models.BooleanField()),
                ('tweet_media_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
